import React from 'react';
import Footer from '../components/Footer';

const Terms = () => {
  return (
    <div className="min-h-screen flex flex-col bg-navy-900 text-gray-300">
      <div className="max-w-4xl mx-auto px-4 py-16 flex-1">
        <h1 className="text-3xl md:text-5xl font-heading font-bold text-white mb-8">Terms of Service</h1>
        <div className="space-y-6 text-sm md:text-base leading-relaxed">
          <p>Welcome to M3 Algox. By using our trading bot services, you agree to these terms.</p>
          
          <h2 className="text-xl font-semibold text-white mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>By accessing and using the M3 Algox platform, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use our services.</p>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">2. Service Description</h2>
          <p>M3 Algox provides automated algorithmic trading software ("bots"). The service requires users to connect their own trading accounts via API. We do not hold client funds directly.</p>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">3. Profit Sharing & Fees</h2>
          <p>Users agree to a profit-sharing model where 30% of the net profits generated by the bot are payable to M3 Algox every 14 days (2 weeks). Additionally, a fixed VPS maintenance fee of ₹1,500/month is required to ensure 24/7 uptime.</p>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">4. User Responsibilities</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li>Maintaining sufficient capital (minimum ₹50,000) in the connected trading account.</li>
            <li>Paying invoices for profit sharing and VPS fees on time. Failure to do so may result in service suspension.</li>
            <li>Keeping API keys and account credentials secure.</li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-8 mb-4">5. Disclaimer of Warranties</h2>
          <p>The service is provided on an "as is" and "as available" basis. M3 Algox makes no guarantees regarding profit, performance, or uptime, though we strive for 99.7% uptime.</p>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Terms;
